# General parameters
dataset: adult
objective: binary

# Cross validation parameters
num_splits: 5
shuffle: True
seed: 221

# Preprocessing parameters
scale: True
target_encode: True
one_hot_encode: False


# About the data
cat_idx: [1,3,5,6,7,8,9,13]
# cat_dims: will be automatically set.
# cat_dims: [9, 16, 7, 15, 6, 5, 2, 42]